### ISSUE TITLE
App is stuck on light theme

### ISSUE THREAD

**Issue by sfwtn** [smolBlackCat/progress-tracker#1]
Hello there, saw this project on Flathub and decided to check it out. From the screenshots it seems that it supports dark theme, but I'm using KDE Plasma and it didn't pick up my theme preference and defaulted to light mode. Would it be possible to add a manual switch?

**Comment by smolBlackCat** [comment]
Thanks for reaching out. Yeah, I'm working on some bug fixes along with some UI enhances. I'll add this to the next minor release

**Comment by Roman19S** [comment]
I have been having the same issue. It's not happening in other GTK apps for me, so I think there is a way to get it to respect the user's theme without a manual toggle

**Comment by smolBlackCat** [comment]
@Roman19S Interesting. By the way, may you inform me of your desktop environment?

You have also mentioned that this issue don't happen on other GTK apps, do you know if those apps are using also libadwaita?

**Comment by Roman19S** [comment]
@smolBlackCat I'm on KDE Plasma 6 and Gnome 43. I have the issue on both. I don't know how to check what theme they are using

**Comment by smolBlackCat** [comment]
Interesting. Are you using custom themes on GNOME 43? If not, toggling the dark mode button doesn't change the application's theme. Is that right?

**Comment by smolBlackCat** [comment]
Yup. I have just tested this on my system. It happens on both the native version and the flatpak version. I'll work on solving this issue ASAP

**Comment by smolBlackCat** [comment]
Newest release solves this problem

**Comment by Roman19S** [comment]
Sorry, I didn't see your earlier message. Thanks for being so quick to fix this!
