### ISSUE TITLE
Cards and Cardlists should be on rename mode by default

### ISSUE THREAD

**Issue by norman2837** [smolBlackCat/progress-tracker#12]
After creating Board and adding List, I suggest that by default after creation you are prompted to rename the List/Board, since you always need to rename it for yourself after creating a List/Board.

**Comment by smolBlackCat** [comment]
Very well, the solution should be very simple. If anything, this might be in the next minor release

**Comment by smolBlackCat** [comment]
Recently pushed commit solves this issue
