### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [smolBlackCat/progress-tracker#3]
Could you verify the Flathub version and add it to the installation category of the README.md file? It will make it a lot easier for people outside of Debian-based distros to discover and use Progress. Here's a link to the documentation on verifying apps on Flathub https://docs.flathub.org/docs/for-app-authors/verification

**Comment by smolBlackCat** [comment]
![Screenshot from 2024-03-29 12-54-19](https://github.com/smolBlackCat/progress-tracker/assets/66385489/e6ea1443-81a1-4947-82c2-fccda011aeac)
App is now verified
