### ISSUE TITLE
Unable to delete boards

### ISSUE THREAD

**Issue by foxtrot222** [smolBlackCat/progress-tracker#32]
Problem : Unable to delete boards because i can't find a way to select boards as menu has button to delete only selected boards. Using tabs i can select a board but as soon as i go to click menu, It gets UN-selected.

App Version : 1.6.0 (Flatpak)
OS : Fedora 41
DE : Gnome 47

https://github.com/user-attachments/assets/905e27ae-9497-4e1e-9427-feae07f4f3ea

**Comment by smolBlackCat** [comment]
Honestly, the board deletion mode is not the most obvious. I'll work on it in the next minor release. For now, here is how you delete boards.


https://github.com/user-attachments/assets/c4f02ee4-ead0-4fdc-bde7-45a7111734dd

**Comment by smolBlackCat** [comment]
The main problem here is because I made application focusing on a keyboard and mouse user. Thanks for pointing this issue out

**Comment by foxtrot222** [comment]
Thank you
