### ISSUE TITLE
Outdated Translations

### ISSUE THREAD

**Issue by smolBlackCat** [smolBlackCat/progress-tracker#9]
After some modifications were made to the [POT file](https://github.com/smolBlackCat/progress-tracker/blob/main/po/progress-tracker.pot), the currently available translations need to be updated.

- [X] Brazilian Portuguese
- [X] Turkish
- [ ] Dutch 
- [ ] Spanish
- [ ] Italian (on review)
- [x] Bulgarian

This issue is important for the next minor release

**Comment by twlvnn** [comment]
I'll update the Bulgarian translation by the end of today and you can expect a pull request.
